.kaniko-build:
  variables:
    KANIKO_ARGS: ""
    KANIKO_BUILD_CONTEXT: $CI_PROJECT_DIR
  stage: build
  tags:
    - gitops
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - |
      if [ -z ${IMAGE_TAG+x} ]; then
        if [ "$CI_COMMIT_REF_NAME" = $CI_DEFAULT_BRANCH ]; then
            VERSION="latest"
          elif [ -n "$CI_COMMIT_TAG" ];then
            NOSLASH=$(echo "$CI_COMMIT_TAG" | tr -s / - )
            SANITIZED="${NOSLASH//[^a-zA-Z0-9.-]/}"
            VERSION="$SANITIZED"
          else \
            NOSLASH=$(echo "$CI_COMMIT_REF_NAME" | tr -s / - )
            SANITIZED="${NOSLASH//[^a-zA-Z0-9-]/}"
            VERSION="branch-$SANITIZED"
          fi
        export IMAGE_TAG=$CI_REGISTRY_IMAGE:$VERSION
      fi
    - echo $IMAGE_TAG
    - mkdir -p /kaniko/.docker
    # Write credentials to access Gitlab Container Registry within the runner/ci
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - |
      if [ -z "$DOCKERFILE_PATH" ]; then
        if [ -f "$KANIKO_BUILD_CONTEXT/Dockerfile" ]; then
          DOCKERFILE_PATH="$KANIKO_BUILD_CONTEXT/Dockerfile"
        elif [ -n "$CONTAINERFILE_PATH" ]; then
          DOCKERFILE_PATH="$CONTAINERFILE_PATH"
        elif [ -f "$KANIKO_BUILD_CONTEXT/Containerfile" ]; then
          DOCKERFILE_PATH="$KANIKO_BUILD_CONTEXT/Containerfile"
        else \
          echo "No suitable configuration for the build context have been found. Please check your configuration."
          exit 1
        fi
      fi
    - echo $DOCKERFILE_PATH
    - /kaniko/executor --context $KANIKO_BUILD_CONTEXT --dockerfile $DOCKERFILE_PATH --destination $IMAGE_TAG $KANIKO_ARGS
kaniko-build:
  extends: .kaniko-build

